# Generated by Django 4.0.5 on 2022-06-28 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_category_name_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
